---
image: golang:1.6

stages:
- test
- build
- selfcheck
- release

cache:
  key: global_cache
  paths:
  - ./glide/
  - vendor/

.docker: &docker
  stage: test
  before_script:
  - source ci/prepare.sh
  tags:
  - docker

static_analysis:
  <<: *docker
  script:
  - make deps deps-tests lint fmt vet complexity

unit_tests:
  <<: *docker
  script:
  - make deps deps-tests test

build:
  <<: *docker
  stage: build
  script:
  - make deps deps-build build_all prepare_sha
  artifacts:
    expire_in: 7d
    paths:
    - out/

licenses_check:
  <<: *docker
  stage: selfcheck
  script:
  - make deps deps-tests license

.release: &release
  <<: *docker
  stage: release
  script:
  - make release RELEASE="$CI_BUILD_NAME"
  tags:
  - release

development:
  <<: *release
  only:
  - branches@tmaczukin/goliscan
  except:
  - master@tmaczukin/goliscan
  environment: development

unstable:
  <<: *release
  only:
  - master@tmaczukin/goliscan
  environment: unstable

stable:
  <<: *release
  only:
  - tags@tmaczukin/goliscan
  environment: stable
